### ISSUE TITLE
Separate ESP from ofApp (GUI)

### ISSUE THREAD

**Issue by nebgnahz** [damellis/ESP#298] opened 2016-07-27 18:46 UTC
In the preparation of a command line program, I would like to reuse as much as possible from ESP.

Currently the cli program has been reusing `TrainingDataManager` and constructing the pipeline manually (https://github.com/damellis/ESP/blob/master/Xcode/ESP/src/cli.cpp#L22). Ideally, I think we should be able to pull off the same user code and run it here.

The biggest problem right now is the entangled dependencies of openFrameworks.

I am using external function (see https://github.com/damellis/ESP/commit/f954bc1d57e2a2cbd9e6799e91da6f3e5df2dc1e) right now. Suggestions welcome.

**Comment by damellis** [comment] 2016-09-10 00:22
Duplicate of #205.

**Closed by damellis** 2016-09-10 00:22 UTC
